server.port=8185
spring.application.name=utils-service

jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://postgres:5432/post_hub
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.default_schema=v1_utils_service
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
spring.flyway.schemas=v1_utils_service

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=utils-service

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs