spring.application.name=utils-service
server.servlet.context-path=/

server.port=8185

#Jwt
jwt.secret=akgbskbYpxNe6F9gT+J86YgQP5TIdiufRrewDunIIx4dfYTamoRazdkG8gTLWzKMUSpDRSXELEtGuEXALJS/hA==

# Database Configuration
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/post_hub_local
spring.datasource.password=${DB_PASSWORD:123qwe}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.default_schema=v1_utils_service
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_utils_service

# Endpoints
end.points.actionLogs=/actionLogs
end.points.id=/{id}
end.points.all=/all
end.points.markAsRead=/markAsRead

#Swagger
swagger.servers.first=http://localhost:8185
swagger.servers.second=
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#Logging Level
logging.level.com.post_hub.utils_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
