spring.application.name=utils-service
server.servlet.context-path=/
server.port=8185

jwt.secret=${JWT_SECRET}

spring.datasource.url=jdbc:postgresql://SG-post-hub-db-7727-pgsql-master.servers.mongodirector.com:5432/postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=v1_utils_service
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_utils_service

swagger.servers.first=http://${SERVER_IP}:8100
swagger.servers.second=http://${SERVER_IP}:8185
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

kafka.enabled=true
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=utils-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.ack-mode=manual

additional.kafka.topic.iam.service.logs=iam-service-logs

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.cloud.consul.enabled=false
spring.cloud.consul.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false