spring.application.name=utils-service
server.servlet.context-path=/
server.port=8185

# JWT
jwt.secret=${JWT_SECRET}

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.default_schema=v1_utils_service
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=v1_utils_service

# Endpoints
end.points.actionLogs=/actionLogs
end.points.id=/{id}
end.points.all=/all
end.points.markAsRead=/markAsRead

# Swagger
swagger.servers.first=http://${SERVER_IP}:8100
swagger.servers.second=http://${SERVER_IP}:8185
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Kafka
spring.kafka.bootstrap-servers=${SERVER_IP}:9092

spring.kafka.consumer.group-id=utils_service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.listener.ack-mode=manual

# Custom Kafka topic
additional.kafka.topic.iam.service.logs=iam_topic_for_demo

# Actuator for health-check
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Consul
spring.cloud.consul.host=${SERVER_IP}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.prefer-ip-address=true

# Logging
logging.level.com.post_hub.utils_service=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.flywaydb=DEBUG
